### ISSUE TITLE
Dataset named "None" appears in Dataset List, and generates Internal Server Error if clicked.

### ISSUE THREAD

**Issue by clynnes** [ESIPFed/usage-based-discovery#30]
# Describe the bug
A dataset named "None" shows up on the right hand panel and generates an Internal Server error.
## To Reproduce
1. Go to UBD tool
2. Click on "Earthquakes"
3. Click "ARIA Damage Proxy Map (Copernicus Sentinel-1) for the Aegean Sea Earthquake on 10/30/2020"
4. Look at the bottom of the Datasets list.
5. Click on "See Dataset"
# Expected behavior
If for whatever reason, harvesting comes back with None, it shouldn't be added to the harvester output.
## Please complete the following information:
- Browser: Safari
- Operating System: Mac

**Comment by parthdarji55** [comment]
i think the correct application that has this error is Topic Earthquakes, Application: ARIA Damage Proxy Map (Copernicus Sentinel-1) on 3/23/2020 for the Croatia Earthquake
