### ISSUE TITLE
Spurious Application Topics

### ISSUE THREAD

**Issue by clynnes** [ESIPFed/usage-based-discovery#34]
# Describe the bug
We have an application topic called "Precipitation", which is not really an application topic, though there are many application topics that use Precipitation (storms, cyclones, floods, agriculture...)
There are several other measurements that don't quite make the cut for application topics:

1. River Heights (measurement)
2. Snowfall (measurement)
3. Precipitation (measurement)
4. Water (too general)
5. Air (too general)
6. Soil Moisture (measurement)
7. Lake Heights (measurement)
8. Hazards (too general)

## To Reproduce
Shows up on home screen when you first bring it up.
# Expected behavior
I don't expect to see application topics that are closer to measurements. 
## Screenshots or Error message
If applicable, add screenshots or Error message to help explain your problem.
## Please complete the following information:
- Browser: All
## Additional context
Also need to combine Cyclones and Hurricanes into Tropical Cyclones.

**Comment by vinnyinverso** [comment]
@clynnes the topics are derived from the applications themselves, i.e. the topics that show up on the landing page is a set of the collection of all topics found from all applications. What this means is that if we edit each application with topic= Precipitation, changing the topic to something else, Precipitation should disappear from the home page. I also think that apps can be recategorized via the 'edit app' page.

**Comment by vinnyinverso** [comment]
I think this is outdated but feel free to reopen if it is still relevant.
